### ISSUE TITLE
La aplicación se detiene al dar tap sobre ítems sin mapa en la sección de 'Ayuda Sismo CDMX'

### ISSUE THREAD

**Issue by jmalonsos** [erikcaffrey/AyudaMexico#20]
Trazas de excepción.
```
09-21 23:42:41.091 31385-31385/io.github.erikcaffrey.ayudamexico E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.github.erikcaffrey.ayudamexico, PID: 31385
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
at android.app.Activity.startActivityForResult(Activity.java:3424)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:28)
at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:143)
at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:781)
at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:896)
at android.support.v4.app.Fragment.startActivity(Fragment.java:981)
at android.support.v4.app.Fragment.startActivity(Fragment.java:970)
at io.github.erikcaffrey.ayudamexico.help.ui.HelpFragment.showDetails(HelpFragment.java:97)
at io.github.erikcaffrey.ayudamexico.help.presenter.HelpPresenter.onItemClick(HelpPresenter.java:49)
at io.github.erikcaffrey.ayudamexico.help.ui.adapter.HelpHolder$1.onClick(HelpHolder.java:58)
```

**Comment by Diego-Franco** [comment]
listo el fix para este crash https://github.com/erikcaffrey/AyudaMexico/commit/a8ae2e2ecb85bb184673bfd2ac4bfc34b7a03af3
